In [1]:
# Support Vector Machine (SVM)

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
df = pd.read_csv("C:/Users/tanma/PuneSeason17CleanedData.csv")
dfm=df.iloc[:-14,:]
dfv=df.iloc[1837:,:]

In [3]:
xm=dfm.iloc[:,1:]
ym=dfm.iloc[:,0]

In [31]:
xt=dfv.iloc[:,1:]
yt=dfv.iloc[:,0]

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(xm,ym,test_size=0.1,random_state =1)

C:\Users\tanma\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [22]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [23]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0, probability= True)
classifier.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=True, random_state=0, shrinking=True, tol=0.001,
  verbose=False)

In [24]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)

In [25]:
y_predprob=classifier.predict_proba(x_test)
y_predprob

array([[9.92035149e-01, 7.96485077e-03],
       [3.00000090e-14, 1.00000000e+00],
       [9.99999862e-01, 1.38489819e-07],
       [9.99999900e-01, 1.00000010e-07],
       [9.99999900e-01, 1.00000010e-07],
       [9.99845621e-01, 1.54378532e-04],
       [9.99588433e-01, 4.11567087e-04],
       [9.98201997e-01, 1.79800326e-03],
       [9.99999900e-01, 1.00000010e-07],
       [9.99841196e-01, 1.58803846e-04],
       [9.99999900e-01, 1.00000010e-07],
       [9.99999900e-01, 1.00000010e-07],
       [9.99999900e-01, 1.00000010e-07],
       [9.99999900e-01, 1.00000010e-07],
       [9.99999900e-01, 1.00000010e-07],
       [6.27021847e-10, 9.99999999e-01],
       [9.85403040e-01, 1.45969598e-02],
       [9.99995167e-01, 4.83284050e-06],
       [2.61151018e-12, 1.00000000e+00],
       [2.62143192e-13, 1.00000000e+00],
       [3.00000090e-14, 1.00000000e+00],
       [9.99999900e-01, 1.00000010e-07],
       [3.00000090e-14, 1.00000000e+00],
       [9.99977868e-01, 2.21316270e-05],
       [1.476631

In [26]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [27]:
cm

array([[164,   0],
       [ 20,   0]], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred, normalize=False)

164

In [29]:
from sklearn.metrics import roc_auc_score
print( roc_auc_score(y_test, y_pred) )

0.5


In [33]:
# Predicting the Unseen set results
y_predun = classifier.predict(xt)
y_predun

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [34]:
y_predprobun =classifier.predict_proba(xt)
y_predprobun

array([[9.99999900e-01, 1.00000010e-07],
       [3.00000090e-14, 1.00000000e+00],
       [9.99999900e-01, 1.00000010e-07],
       [9.99999900e-01, 1.00000010e-07],
       [9.99999035e-01, 9.64539265e-07],
       [9.99999900e-01, 1.00000010e-07],
       [1.64334450e-01, 8.35665550e-01],
       [9.99999900e-01, 1.00000010e-07],
       [9.99999900e-01, 1.00000010e-07],
       [8.57062908e-10, 9.99999999e-01],
       [9.98860782e-01, 1.13921760e-03],
       [9.86891963e-01, 1.31080374e-02],
       [9.99996634e-01, 3.36602558e-06],
       [9.99999900e-01, 1.00000010e-07]])